# Generated by Django 5.0.1 on 2024-02-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='museum_images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('artist', models.CharField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('artist', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artwork_images/')),
                ('date_created', models.DateField(null=True)),
                ('century', models.CharField(max_length=200, null=True)),
                ('categories', models.ManyToManyField(to='catalog.category')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.museum')),
            ],
        ),
        migrations.CreateModel(
            name='MuseumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('opening_hours', models.TextField()),
                ('website', models.URLField()),
                ('museum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.museum')),
            ],
        ),
    ]
