# Generated by Django 5.0.1 on 2024-02-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='artist',
        ),
        migrations.AddField(
            model_name='museum',
            name='contact_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='museum',
            name='contact_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='museum',
            name='opening_hours',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MuseumProfile',
        ),
    ]
